//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOtomasyon.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSummary
    {
        public int CustumerId { get; set; }
        public string NameSurname { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<decimal> WillGive { get; set; }
        public int CustomerSummaryId { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
